---
networks:
  rtorrent: {}

services:
  rtorrent:
    container_name: rtorrent
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      # - "RTORRENT_SCGI_PORT=5000"
      - "RTORRENT_OPTS=-o system.daemon.set=true -o import=/config/rtorrent.rc"
      # - "RTORRENT_OPTS=-o system.daemon.set=true -o network.scgi.open_port=0.0.0.0:5000"
      - "TZ=${TZ}"
    image: rtorrent
    networks:
      - rtorrent
    restart: unless-stopped
    volumes:
      - "${MOUNT}/downloads:${MOUNT}/downloads"