#!/usr/bin/with-contenv bash

PUID=${PUID:-82}
PGID=${PGID:-82}

groupmod --non-unique --gid "$PGID" www-data
usermod  --non-unique --uid "$PUID" www-data

echo "
-------------------------------------
GID/UID
-------------------------------------"
echo "
Apache uid:    $(id -u lighttpd)
Apache gid:    $(id -g lighttpd)
-------------------------------------"