#!/usr/bin/with-contenv bash

PUID=${PUID:-82}
PGID=${PGID:-82}

groupmod --non-unique --gid "$PGID" www-data
usermod  --non-unique --uid "$PUID" www-data

echo "
-------------------------------------
GID/UID
-------------------------------------"
echo "
Apache uid:    $(id -u www-data)
Apache gid:    $(id -g www-data)
-------------------------------------"

chown -R www-data:www-data \
    /srv/www/rutorrent \
    /config